### ISSUE TITLE
Measuring RSS for threads might not tell the whole story

### ISSUE THREAD

**Issue by matklad** [jimblandy/context-switch#4]
Hey, I've recently been (rightfully) [grilled on hackernews](https://news.ycombinator.com/item?id=26441558) for not measuring memory usage of threads properly, and I think this benchmark suffers from the same problem. The crux of the issue is that a thread is a resource managed by the kernel, so some memory overhead ends up in kernel's own data structures, and is not visible in RSS. In contrast, async tasks are managed entirely in user space, and RSS indeed accounts for everything 

In particular, each thread's stack needs an entry in page table, and, as stacks are sparsely spread out across the memory, this allocates pages for page table entries themselves. 

By looking at the `/proc/{pid}/status`, I see `VmPTE:	   2892 kB` for 1000 thread async brigade, which is an additional 2.8k overhead per thread.

**Comment by jimblandy** [comment]
Thanks for pointing this out. I did record information from `/proc/slabinfo` while creating variable numbers of threads, and applied a linear regression to that. It came to about 11kiB per thread.

I mention this briefly in the first section of `README.md`, but I never explain how I obtained that number. And unfortunately, I don't seem to have kept around that script.

**Comment by jimblandy** [comment]
> That being said, creating thousands of native threads has lots of other pitfalls, including stack ones - would not recommend as a general strategy.

**Comment by jimblandy** [comment]
From the HN comments:

> That being said, creating thousands of native threads has lots of other pitfalls, including stack ones - would not recommend as a general strategy.

While I don't think this is _wrong_, exactly, this is a great example of the sort of broad advice without explanation that you can find in such abundance anywhere programmers gather to chew the fat. But it is maddeningly difficult to trace it back to anything observable or reproducible, or even very concrete. [Eli Bendersky](https://eli.thegreenplace.net/2018/measuring-context-switching-and-memory-overheads-for-linux-threads/) was a notable and much-appreciated exception. One goal of this repo was to try to add to that.

**Comment by matklad** [comment]
Uhu, strong +1 to “ is maddeningly difficult to trace it back to anything observable or reproducible, or even very concrete”. I, for example, still don’t understand what *exactly* is the limiting factor for threads, one you are past easy ulimit-like things.

kudos for publishing this benchmark, it, I think, is he most thoroughly researched one at the moment!
